// Angular-Challenge/src/app/components/event-list/event-list.component.ts
import { Component, Input } from '@angular/core';
import { Event } from '../../interfaces';

@Component({
  selector: 'app-event-list',
  templateUrl: './event-list.component.html',
  styleUrl: './event-list.component.scss',
})
export class EventListComponent {
  @Input() events: Event[] = [];
  @Input() loading: boolean = false;
}

<nz-list [nzLoading]="loading" [nzDataSource]="events" [nzRenderItem]="item" [nzBordered]="false">
  <ng-template #item let-event>
    <nz-list-item>
      <nz-list-item-meta [nzAvatar]="event.images[0]?.url" [nzTitle]="event.name" [nzDescription]="(event.dates.start.localDate | date:'MM/dd/YYYY') +' | '+ ( event | parseCity)"></nz-list-item-meta>
      <img [src]="event.images[0]?.url" alt="{{event.name}}" width="100" />
    </nz-list-item>
  </ng-template>
</nz-list>

// React-Challenge/src/components/eventList/index.tsx
import { memo } from 'react';
import { List, Avatar } from 'antd';
import { Event } from 'interface';
import { DATE_FORMAT, parseCity } from 'utilities';
import dayjs from 'dayjs';

type EventListProps = {
  events: Event[];
  loading: boolean;
};

export const EventList = memo(({ events, loading }: EventListProps) => {
  return (
    <List
      loading={loading}
      itemLayout="vertical"
      size="large"
      dataSource={events}
      renderItem={(event) => (
        <List.Item
          key={event.id}
          extra={<img width={100} alt={event.name} src={event.images[0].url} />}
        >
          <List.Item.Meta
            avatar={<Avatar src={event.images[0].url} />}
            title={event.name}
            description={
              <>
                <p>{`${dayjs(event.dates.start.dateTime).format(DATE_FORMAT)} | ${parseCity(event)}`}</p>
              </>
            }
          />
        </List.Item>
      )}
    />
  );
});

export default EventList;
