// Angular-Challenge/src/app/components/event-filter/event-filter.component.ts
import { Component, Output, EventEmitter, Input } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import dayjs from 'dayjs';
import { FormFilterParams } from '../../interfaces';

@Component({
  selector: 'app-event-filter',
  templateUrl: './event-filter.component.html',
  styleUrls: ['./event-filter.component.scss'],
})
export class EventFilterComponent {
  filterForm: FormGroup;
  @Output() filterChanged = new EventEmitter<FormFilterParams>();
  @Input() loading: boolean = false;

  constructor(private fb: FormBuilder) {
    this.filterForm = this.fb.group({
      location: [''],
      startDate: [null],
      endDate: [null],
      sortBy: ['date'],
      direction: ['desc'],
    });
  }

  onStartDateChange(date: Date): void {
    if (date) {
      this.filterForm.get('endDate')?.updateValueAndValidity();
    }
  }

  onEndDateChange(date: Date): void {
    if (date) {
      this.filterForm.get('startDate')?.updateValueAndValidity();
    }
  }

  disabledStartDate = (startValue: Date): boolean => {
    const endDate = this.filterForm.get('endDate')?.value;
    if (!startValue || !endDate) {
      return false;
    }
    return dayjs(startValue).isAfter(dayjs(endDate));
  };

  disabledEndDate = (endValue: Date): boolean => {
    const startDate = this.filterForm.get('startDate')?.value;
    if (!endValue || !startDate) {
      return false;
    }
    return dayjs(endValue).isBefore(dayjs(startDate));
  };

  onSubmit(): void {
    if (this.filterForm.valid) {
      const formValues = this.filterForm.value;
      this.filterChanged.emit({
        ...formValues,
      });
    }
  }
}

<form nz-form [formGroup]="filterForm" (ngSubmit)="onSubmit()">
  <nz-row [nzGutter]="16">
    <nz-col [nzSpan]="24">
      <nz-form-item>
        <nz-form-label [nzSm]="6" nzFor="location">Location</nz-form-label>
        <nz-form-control [nzSm]="14">
          <input nz-input formControlName="location" id="location" />
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>

  <nz-row [nzGutter]="16">
    <nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzSm]="6" nzFor="startDate">Start Date</nz-form-label>
        <nz-form-control [nzSm]="14">
          <nz-date-picker formControlName="startDate" nzFormat="MM/dd/yyyy" id="startDate" (ngModelChange)="onStartDateChange($event)" [nzDisabledDate]="disabledStartDate"></nz-date-picker>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzSm]="6" nzFor="endDate">End Date</nz-form-label>
        <nz-form-control [nzSm]="14">
          <nz-date-picker formControlName="endDate" nzFormat="MM/dd/yyyy" id="endDate" (ngModelChange)="onEndDateChange($event)" [nzDisabledDate]="disabledEndDate"></nz-date-picker>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>

  <nz-row [nzGutter]="16">
    <nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzSm]="6" nzFor="sortBy">Sort By</nz-form-label>
        <nz-form-control [nzSm]="14">
          <nz-select formControlName="sortBy">
            <nz-option nzValue="date" nzLabel="Date"></nz-option>
            <nz-option nzValue="name" nzLabel="Name"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
    <nz-col [nzSpan]="12">
      <nz-form-item>
        <nz-form-label [nzSm]="6" nzFor="direction">Direction</nz-form-label>
        <nz-form-control [nzSm]="14">
          <nz-select formControlName="direction">
            <nz-option nzValue="asc" nzLabel="Ascending"></nz-option>
            <nz-option nzValue="desc" nzLabel="Descending"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>

  <nz-row>
    <nz-col [nzSpan]="24">
      <nz-form-item>
        <nz-form-control [nzSm]="14" [nzOffset]="6">
          <button nz-button [nzLoading]="loading" nzType="primary">Search</button>
        </nz-form-control>
      </nz-form-item>
    </nz-col>
  </nz-row>
</form>

// React-Challenge/src/components/eventFilter/index.tsx
import { memo } from 'react';
import { Form, Input, DatePicker, Select, Button, Row, Col } from 'antd';
import { FormFilterParams } from 'interface';
import style from './index.module.scss';
import { DATE_FORMAT } from 'utilities';
import { useDateValidation } from 'hooks/useDateValidation';

const { Option } = Select;

type EventFilterProps = {
  loading: boolean;
  onFilterChanged?: (params: FormFilterParams) => void;
};

export const EventFilter = memo(
  ({ loading, onFilterChanged }: EventFilterProps) => {
    const [form] = Form.useForm<FormFilterParams>();
    const { disabledEndDate, disabledStartDate } = useDateValidation(form);
    return (
      <Form form={form} onFinish={onFilterChanged} layout="vertical">
        <Row gutter={16}>
          <Col span={12}>
            <Form.Item label="Location" name="city">
              <Input />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={16}>
          <Col span={12}>
            <Form.Item label="Start Date" name="startDate">
              <DatePicker
                format={DATE_FORMAT}
                disabledDate={disabledStartDate}
              />
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item label="End Date" name="endDate">
              <DatePicker format={DATE_FORMAT} disabledDate={disabledEndDate} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={16}>
          <Col span={12}>
            <Form.Item label="Sort By" name="sortBy" initialValue="date">
              <Select>
                <Option value="date">Date</Option>
                <Option value="name">Name</Option>
              </Select>
            </Form.Item>
          </Col>
          <Col span={12}>
            <Form.Item label="Direction" name="direction" initialValue="desc">
              <Select>
                <Option value="asc">Ascending</Option>
                <Option value="desc">Descending</Option>
              </Select>
            </Form.Item>
          </Col>
        </Row>
        <Row>
          <Col span={24}>
            <Form.Item>
              <Button
                className={style.button}
                type="primary"
                htmlType="submit"
                loading={loading}
              >
                Search
              </Button>
            </Form.Item>
          </Col>
        </Row>
      </Form>
    );
  },
);

export default EventFilter;
